# Shiki（式） - Label Classification System (53 labels)
# Used in both CLI mode (task metadata) and GitHub mode (Issue/PR labels)

priority:
  - name: "P0-critical"
    color: "b60205"
    description: "Must fix immediately, blocks everything"
  - name: "P1-high"
    color: "d93f0b"
    description: "Important, should be addressed soon"
  - name: "P2-medium"
    color: "fbca04"
    description: "Normal priority"
  - name: "P3-low"
    color: "0e8a16"
    description: "Nice to have, can wait"

status:
  - name: "status/pending"
    color: "ededed"
    description: "Not yet started"
  - name: "status/in-progress"
    color: "0075ca"
    description: "Currently being worked on"
  - name: "status/review"
    color: "7057ff"
    description: "Awaiting review"
  - name: "status/blocked"
    color: "d73a4a"
    description: "Blocked by dependency or issue"
  - name: "status/completed"
    color: "0e8a16"
    description: "Done and verified"
  - name: "status/failed"
    color: "b60205"
    description: "Failed, needs attention"

type:
  - name: "type/feature"
    color: "a2eeef"
    description: "New feature implementation"
  - name: "type/bugfix"
    color: "d73a4a"
    description: "Bug fix"
  - name: "type/refactor"
    color: "e4e669"
    description: "Code refactoring"
  - name: "type/test"
    color: "bfd4f2"
    description: "Test creation or update"
  - name: "type/docs"
    color: "0075ca"
    description: "Documentation"
  - name: "type/infra"
    color: "d4c5f9"
    description: "Infrastructure/CI/CD"
  - name: "type/security"
    color: "b60205"
    description: "Security-related change"
  - name: "type/design"
    color: "c5def5"
    description: "Architecture/design work"

authority:
  - name: "authority/coordinator"
    color: "ff9500"
    description: "Requires coordinator-level authority"
  - name: "authority/executor"
    color: "0075ca"
    description: "Executor-level authority sufficient"
  - name: "authority/monitor"
    color: "bfd4f2"
    description: "Monitor/read-only authority"

theta:
  - name: "theta/1-understand"
    color: "c5def5"
    description: "Phase: Goal comprehension"
  - name: "theta/2-generate"
    color: "bfd4f2"
    description: "Phase: Plan generation"
  - name: "theta/3-allocate"
    color: "d4c5f9"
    description: "Phase: Resource allocation"
  - name: "theta/4-execute"
    color: "0075ca"
    description: "Phase: Implementation"
  - name: "theta/5-verify"
    color: "7057ff"
    description: "Phase: Verification"
  - name: "theta/6-integrate"
    color: "0e8a16"
    description: "Phase: Integration"

size:
  - name: "size/XS"
    color: "ededed"
    description: "< 30 min estimated"
  - name: "size/S"
    color: "c5def5"
    description: "30 min - 2 hours"
  - name: "size/M"
    color: "bfd4f2"
    description: "2 - 4 hours"
  - name: "size/L"
    color: "d4c5f9"
    description: "4 - 8 hours"
  - name: "size/XL"
    color: "7057ff"
    description: "8+ hours, consider splitting"

engine:
  - name: "engine/claude-team"
    color: "c2e0c6"
    description: "Assigned to Claude Agent Teams"
  - name: "engine/codex"
    color: "fef2c0"
    description: "Assigned to Codex"
  - name: "engine/human"
    color: "f9d0c4"
    description: "Requires human intervention"
  - name: "engine/claude-leader"
    color: "0e8a16"
    description: "Assigned to Claude team leader"
  - name: "engine/claude-member"
    color: "c2e0c6"
    description: "Assigned to Claude team member"

automation:
  - name: "auto/plan"
    color: "c5def5"
    description: "Automated planning"
  - name: "auto/implement"
    color: "0075ca"
    description: "Automated implementation"
  - name: "auto/review"
    color: "7057ff"
    description: "Automated review"
  - name: "auto/ci-fix"
    color: "d73a4a"
    description: "Automated CI fix"
  - name: "auto/merge"
    color: "0e8a16"
    description: "Auto-mergeable"
  - name: "auto/dag-batch"
    color: "d4c5f9"
    description: "Part of DAG batch execution"

workflow:
  - name: "ai-goal"
    color: "fbca04"
    description: "Shiki goal issue"
  - name: "ai-plan"
    color: "c5def5"
    description: "Shiki plan PR"
  - name: "ai-codex"
    color: "fef2c0"
    description: "Codex-generated PR"
  - name: "needs-review"
    color: "7057ff"
    description: "Awaiting human or AI review"
  - name: "ci-fix"
    color: "d73a4a"
    description: "CI failure fix"
  - name: "worktree"
    color: "d4c5f9"
    description: "Created in git worktree"
  - name: "dag-node"
    color: "bfd4f2"
    description: "Part of DAG execution graph"

mode:
  - name: "mode/cli"
    color: "c2e0c6"
    description: "Originated from CLI mode"
  - name: "mode/github"
    color: "0075ca"
    description: "Originated from GitHub mode"
