#!/usr/bin/env python3
"""Argparse construction and command dispatch for the Shiki CLI."""

from __future__ import annotations

import argparse
import sys
from typing import Iterable

from shiki_contracts import DEFAULT_REQUIRED_CHECKS
from shiki_bootstrap import cmd_bootstrap_github, cmd_init, cmd_preflight, cmd_start
from shiki_github import cmd_github_issue, cmd_github_pr
from shiki_installer import DEFAULT_CLAUDE_COMMAND_PATH, DEFAULT_CODEX_SKILL_PATH, DEFAULT_GLOBAL_COMMAND_PATH, cmd_install_command, cmd_install_global, cmd_install_target, cmd_status
from shiki_process import ShikiError
from shiki_runtime import cmd_daemon_enqueue_plan, cmd_daemon_run, cmd_doctor, cmd_runner_codex, cmd_runner_execute, cmd_runner_next, cmd_smoke_live
from shiki_tasks import cmd_dispatch_check, cmd_goal_complete, cmd_goal_create, cmd_handoff_repair, cmd_handoff_task, cmd_issue_plan, cmd_lock_acquire, cmd_plan_guide, cmd_plan_ingest, cmd_repair_packet, cmd_run, cmd_task_status, cmd_worktree_allocate

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="shiki")
    subcommands = parser.add_subparsers(dest="command", required=True)

    init = subcommands.add_parser("init", help="Install Shiki into a target repo and publish it to GitHub")
    init.add_argument("target", help="Target repository path")
    init.add_argument("--repo", required=True, help="GitHub repository as OWNER/NAME")
    init.add_argument("--branch", default="main", help="Default branch, default main")
    init.add_argument("--private", action="store_true", help="Create a private repo")
    init.add_argument("--public", action="store_true", help=argparse.SUPPRESS)
    init.add_argument("--force", action="store_true", help="Overwrite existing target files")
    init.add_argument("--validate", action=argparse.BooleanOptionalAction, default=True)
    init.add_argument("--commit", action=argparse.BooleanOptionalAction, default=True)
    init.add_argument("--commit-message", default="shiki: initialize GitHub-first control plane")
    init.add_argument("--push", action=argparse.BooleanOptionalAction, default=True)
    init.add_argument("--set-secret", action=argparse.BooleanOptionalAction, default=True)
    init.add_argument("--secret-env", default="CLAUDE_CODE_OAUTH_TOKEN")
    init.add_argument("--protect", action=argparse.BooleanOptionalAction, default=True)
    init.add_argument("--adopt-existing-repo", action="store_true", help="Explicitly rewrite an existing origin to the requested GitHub repo")
    init.add_argument("--execute", action="store_true", help="Execute bootstrap/init mutations; default is dry-run")
    init.add_argument("--i-understand", action="store_true", help="Alias for --execute")
    init.add_argument("--required-check", action="append", default=list(DEFAULT_REQUIRED_CHECKS))
    init.set_defaults(func=cmd_init)

    preflight = subcommands.add_parser("preflight", help="Check whether a target repo is ready for Shiki")
    preflight.add_argument("target", nargs="?", default=".", help="Target repository path")
    preflight.add_argument("--require-github", action="store_true", help="Fail unless target is connected to GitHub")
    preflight.set_defaults(func=cmd_preflight)

    github = subcommands.add_parser("bootstrap-platform", help="Initialize and publish the Shiki platform repo to GitHub")
    github.add_argument("--repo", help="GitHub repository as OWNER/NAME")
    github.add_argument("--branch", default=None, help="Default branch, default main")
    github.add_argument("--private", action="store_true", help="Create a private repo")
    github.add_argument("--public", action="store_true", help=argparse.SUPPRESS)
    github.add_argument("--commit", action=argparse.BooleanOptionalAction, default=True)
    github.add_argument("--commit-message", default="shiki: bootstrap control plane")
    github.add_argument("--push", action=argparse.BooleanOptionalAction, default=True)
    github.add_argument("--set-secret", action=argparse.BooleanOptionalAction, default=True)
    github.add_argument("--secret-env", default="CLAUDE_CODE_OAUTH_TOKEN")
    github.add_argument("--protect", action=argparse.BooleanOptionalAction, default=True)
    github.add_argument("--adopt-existing-repo", action="store_true", help="Explicitly rewrite an existing origin to the requested GitHub repo")
    github.add_argument("--execute", action="store_true", help="Execute bootstrap mutations; default is dry-run")
    github.add_argument("--i-understand", action="store_true", help="Alias for --execute")
    github.add_argument("--required-check", action="append", default=list(DEFAULT_REQUIRED_CHECKS))
    github.set_defaults(func=cmd_bootstrap_github)

    deprecated = subcommands.add_parser("bootstrap-github", help="Deprecated alias for bootstrap-platform")
    deprecated.add_argument("--repo", help="GitHub repository as OWNER/NAME")
    deprecated.add_argument("--branch", default=None, help="Default branch, default main")
    deprecated.add_argument("--private", action="store_true", help="Create a private repo")
    deprecated.add_argument("--public", action="store_true", help=argparse.SUPPRESS)
    deprecated.add_argument("--commit", action=argparse.BooleanOptionalAction, default=True)
    deprecated.add_argument("--commit-message", default="shiki: bootstrap control plane")
    deprecated.add_argument("--push", action=argparse.BooleanOptionalAction, default=True)
    deprecated.add_argument("--set-secret", action=argparse.BooleanOptionalAction, default=True)
    deprecated.add_argument("--secret-env", default="CLAUDE_CODE_OAUTH_TOKEN")
    deprecated.add_argument("--protect", action=argparse.BooleanOptionalAction, default=True)
    deprecated.add_argument("--adopt-existing-repo", action="store_true", help="Explicitly rewrite an existing origin to the requested GitHub repo")
    deprecated.add_argument("--execute", action="store_true", help="Execute bootstrap mutations; default is dry-run")
    deprecated.add_argument("--i-understand", action="store_true", help="Alias for --execute")
    deprecated.add_argument("--required-check", action="append", default=list(DEFAULT_REQUIRED_CHECKS))
    deprecated.set_defaults(func=cmd_bootstrap_github)

    target = subcommands.add_parser("install-target", help="Install Shiki template files only; GitHub-first setup uses init")
    target.add_argument("target", help="Target repository path")
    target.add_argument("--local-only", action="store_true", help="Allow template-only install without GitHub bootstrap")
    target.add_argument("--force", action="store_true", help="Overwrite existing files")
    target.add_argument("--validate", action=argparse.BooleanOptionalAction, default=True)
    target.set_defaults(func=cmd_install_target)

    install = subcommands.add_parser("install-command", help="Install a shiki command symlink")
    install.add_argument("--path", default=DEFAULT_GLOBAL_COMMAND_PATH)
    install.set_defaults(func=cmd_install_command)

    global_install = subcommands.add_parser("install-global", help="Install global Shiki CLI, Claude slash command, and Codex skill")
    global_install.add_argument("--path", default=DEFAULT_GLOBAL_COMMAND_PATH)
    global_install.add_argument("--claude-command", action=argparse.BooleanOptionalAction, default=True)
    global_install.add_argument("--claude-command-path", default=DEFAULT_CLAUDE_COMMAND_PATH)
    global_install.add_argument("--codex-skill", action=argparse.BooleanOptionalAction, default=True)
    global_install.add_argument("--codex-skill-path", default=DEFAULT_CODEX_SKILL_PATH)
    global_install.set_defaults(func=cmd_install_global)

    status = subcommands.add_parser("status", help="Show local Shiki CLI configuration")
    status.set_defaults(func=cmd_status)

    doctor = subcommands.add_parser("doctor", help="Check Shiki runtime auth and entrypoint readiness")
    doctor.add_argument("--json", action="store_true", help="Print machine-readable status")
    doctor.set_defaults(func=cmd_doctor)

    start = subcommands.add_parser("start", help="One-command interactive Shiki project setup and first run")
    start.add_argument("target_positional", nargs="?", help="Target repository path")
    start.add_argument("--target", default=".", help="Target repository path")
    start.add_argument("--answers-file", help="JSON answers for non-interactive start")
    start.add_argument("--repo", help="GitHub repository as OWNER/NAME")
    start.add_argument("--project-name")
    start.add_argument("--goal")
    start.add_argument("--outcome")
    start.add_argument("--skills-dir", help="Engineering skills directory used by Skill Gate")
    start.add_argument("--completion-condition", action="append", default=[])
    start.add_argument("--non-goal", action="append", default=[])
    start.add_argument("--risk-level", choices=["low", "medium", "high", "critical"])
    start.add_argument("--required-skill", action="append", default=[])
    start.add_argument("--task-title")
    start.add_argument("--task-scope")
    start.add_argument("--acceptance-check", action="append", default=[])
    start.add_argument("--lock", action="append", default=[])
    start.add_argument("--branch", default="main")
    start.add_argument("--private", action="store_true", help="Create a private repo")
    start.add_argument("--public", action="store_true", help=argparse.SUPPRESS)
    start.add_argument("--force", action="store_true", help="Overwrite existing target files during init")
    start.add_argument("--validate", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--commit", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--commit-message", default="shiki: initialize GitHub-first control plane")
    start.add_argument("--push", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--set-secret", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--secret-env", default="CLAUDE_CODE_OAUTH_TOKEN")
    start.add_argument("--protect", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--adopt-existing-repo", action="store_true", help="Explicitly rewrite an existing origin during init")
    start.add_argument("--execute", action="store_true", help="Execute bootstrap/init mutations; default is dry-run for uninitialized targets")
    start.add_argument("--i-understand", action="store_true", help="Alias for --execute")
    start.add_argument("--required-check", action="append", default=list(DEFAULT_REQUIRED_CHECKS))
    start.add_argument("--create-issues", action=argparse.BooleanOptionalAction, default=True)
    start.add_argument("--create-handoffs", action=argparse.BooleanOptionalAction, default=True)
    start.set_defaults(func=cmd_start)

    plan = subcommands.add_parser("plan", help="Ingest and guide grill-with-docs plans")
    plan_subcommands = plan.add_subparsers(dest="plan_command", required=True)
    plan_ingest = plan_subcommands.add_parser("ingest", help="Persist a grill-with-docs plan as machine-readable Shiki input")
    plan_ingest.add_argument("--target", default=".", help="Target repository path")
    plan_ingest.add_argument("--plan-file", required=True, help="JSON plan produced after grill-with-docs")
    plan_ingest.set_defaults(func=cmd_plan_ingest)
    plan_guide = plan_subcommands.add_parser("guide", help="Show the user-facing path from a prompt to a runnable plan")
    plan_guide.add_argument("--target", default=".", help="Target repository path")
    plan_guide.add_argument("--prompt", help="Goal or task prompt to guide")
    plan_guide.set_defaults(func=cmd_plan_guide)

    run_command = subcommands.add_parser("run", help="Run an ingested plan through Goal, Task DAG, locks, and dispatch setup")
    run_command.add_argument("--target", default=".", help="Target repository path")
    run_command.add_argument("--plan", required=True, help="Plan id like P-0001 or path to a grilled plan JSON")
    run_command.set_defaults(func=cmd_run)

    daemon = subcommands.add_parser("daemon", help="Run the Shiki background inbox processor")
    daemon_subcommands = daemon.add_subparsers(dest="daemon_command", required=True)
    daemon_enqueue = daemon_subcommands.add_parser("enqueue-plan", help="Queue a grilled plan for daemon processing")
    daemon_enqueue.add_argument("--target", default=".", help="Target repository path")
    daemon_enqueue.add_argument("--plan-file", required=True)
    daemon_enqueue.set_defaults(func=cmd_daemon_enqueue_plan)
    daemon_run = daemon_subcommands.add_parser("run", help="Process queued Shiki inbox items")
    daemon_run.add_argument("--target", default=".", help="Target repository path")
    daemon_run.add_argument("--once", action="store_true", help="Process at most one item and exit")
    daemon_run.add_argument("--interval", type=float, default=5.0, help="Polling interval in seconds")
    daemon_run.set_defaults(func=cmd_daemon_run)

    runner = subcommands.add_parser("runner", help="Pick up and execute dispatchable Shiki tasks")
    runner_subcommands = runner.add_subparsers(dest="runner_command", required=True)
    runner_next = runner_subcommands.add_parser("next", help="Return the next dispatchable task")
    runner_next.add_argument("--target", default=".", help="Target repository path")
    runner_next.set_defaults(func=cmd_runner_next)
    runner_execute = runner_subcommands.add_parser("execute", help="Execute a command for a ready task and record evidence")
    runner_execute.add_argument("--target", default=".", help="Target repository path")
    runner_execute.add_argument("--task-id", required=True)
    runner_execute.add_argument("--command", required=True)
    runner_execute.set_defaults(func=cmd_runner_execute)
    runner_codex = runner_subcommands.add_parser("codex", help="Run Codex autonomously for a ready Shiki task")
    runner_codex.add_argument("--target", default=".", help="Target repository path")
    runner_codex.add_argument("--task-id", required=True)
    runner_codex.add_argument("--dry-run", action="store_true", help="Show the Codex dispatch without executing it")
    runner_codex.add_argument("--force", action="store_true", help="Run even if the task runtime is not codex")
    runner_codex.set_defaults(func=cmd_runner_codex)

    smoke = subcommands.add_parser("smoke", help="Run live Shiki smoke checks against a GitHub-backed target")
    smoke_subcommands = smoke.add_subparsers(dest="smoke_command", required=True)
    smoke_live = smoke_subcommands.add_parser("live", help="Verify plan/run and optional GitHub issue/PR creation")
    smoke_live.add_argument("--target", default=".", help="Target repository path")
    smoke_live.add_argument("--plan-file", required=True)
    smoke_live.add_argument("--dry-run", action="store_true", help="Run local plan orchestration without GitHub issue/PR creation")
    smoke_live.add_argument("--execute-github", action="store_true", help="Also create GitHub issue and PR evidence")
    smoke_live.add_argument("--push-branch", action="store_true", help="Create, commit, and push the smoke task branch before PR creation")
    smoke_live.add_argument("--base", default="main")
    smoke_live.set_defaults(func=cmd_smoke_live)

    goal = subcommands.add_parser("goal", help="Manage Shiki goals")
    goal_subcommands = goal.add_subparsers(dest="goal_command", required=True)
    goal_create = goal_subcommands.add_parser("create", help="Register a GitHub-first Shiki goal")
    goal_create.add_argument("--target", default=".", help="Target repository path")
    goal_create.add_argument("--title", required=True)
    goal_create.add_argument("--outcome", required=True)
    goal_create.add_argument("--completion-condition", action="append", default=[])
    goal_create.add_argument("--non-goal", action="append", default=[])
    goal_create.add_argument("--risk-level", default="low", choices=["low", "medium", "high", "critical"])
    goal_create.add_argument("--required-skill", action="append", default=[])
    goal_create.add_argument("--acceptance-evidence", action="append", default=[])
    goal_create.add_argument("--github-issue", type=int)
    goal_create.set_defaults(func=cmd_goal_create)

    goal_complete = goal_subcommands.add_parser("complete", help="Judge goal completion from task evidence")
    goal_complete.add_argument("--target", default=".", help="Target repository path")
    goal_complete.add_argument("goal_id")
    goal_complete.add_argument("--summary")
    goal_complete.set_defaults(func=cmd_goal_complete)

    issue = subcommands.add_parser("issue", help="Plan vertical-slice Shiki tasks")
    issue_subcommands = issue.add_subparsers(dest="issue_command", required=True)
    issue_plan = issue_subcommands.add_parser("plan", help="Register a task and update the task DAG")
    issue_plan.add_argument("--target", default=".", help="Target repository path")
    issue_plan.add_argument("--goal-id", required=True)
    issue_plan.add_argument("--title", required=True)
    issue_plan.add_argument("--scope", required=True)
    issue_plan.add_argument("--non-goal", action="append", default=[])
    issue_plan.add_argument("--dependency", action="append", default=[])
    issue_plan.add_argument("--lock", action="append", default=[])
    issue_plan.add_argument("--runtime", default="codex", choices=["codex", "claude-code", "github-actions", "hermes-runner", "human", "other"])
    issue_plan.add_argument("--risk-level", default="low", choices=["low", "medium", "high", "critical"])
    issue_plan.add_argument("--required-skill", action="append", default=[])
    issue_plan.add_argument("--acceptance-check", action="append", required=True)
    issue_plan.add_argument("--expected-branch")
    issue_plan.add_argument("--expected-pr", type=int)
    issue_plan.add_argument("--github-issue", type=int)
    issue_plan.set_defaults(func=cmd_issue_plan)

    lock = subcommands.add_parser("lock", help="Manage Shiki task locks")
    lock_subcommands = lock.add_subparsers(dest="lock_command", required=True)
    lock_acquire = lock_subcommands.add_parser("acquire", help="Acquire declared locks for a task")
    lock_acquire.add_argument("--target", default=".", help="Target repository path")
    lock_acquire.add_argument("--owner", default="shiki-cli")
    lock_acquire.add_argument("task_id")
    lock_acquire.set_defaults(func=cmd_lock_acquire)

    dispatch = subcommands.add_parser("dispatch", help="Run dispatch readiness checks")
    dispatch_subcommands = dispatch.add_subparsers(dest="dispatch_command", required=True)
    dispatch_check = dispatch_subcommands.add_parser("check", help="Check whether a task may be dispatched")
    dispatch_check.add_argument("--target", default=".", help="Target repository path")
    dispatch_check.add_argument("--require-worktree", action="store_true")
    dispatch_check.add_argument("task_id")
    dispatch_check.set_defaults(func=cmd_dispatch_check)

    worktree = subcommands.add_parser("worktree", help="Manage Shiki worktree records")
    worktree_subcommands = worktree.add_subparsers(dest="worktree_command", required=True)
    worktree_allocate = worktree_subcommands.add_parser("allocate", help="Allocate a task worktree record")
    worktree_allocate.add_argument("--target", default=".", help="Target repository path")
    worktree_allocate.add_argument("--branch")
    worktree_allocate.add_argument("--path")
    worktree_allocate.add_argument("--create", action="store_true", help="Also run git worktree add")
    worktree_allocate.add_argument("task_id")
    worktree_allocate.set_defaults(func=cmd_worktree_allocate)

    repair = subcommands.add_parser("repair", help="Manage bounded repair packets")
    repair_subcommands = repair.add_subparsers(dest="repair_command", required=True)
    repair_packet = repair_subcommands.add_parser("packet", help="Create a bounded repair packet")
    repair_packet.add_argument("--target", default=".", help="Target repository path")
    repair_packet.add_argument("--task-id", required=True)
    repair_packet.add_argument("--pr", required=True, type=int)
    repair_packet.add_argument("--attempt", default=1, type=int)
    repair_packet.add_argument("--failing-item", action="append", default=[])
    repair_packet.add_argument("--failing-acceptance-criteria", action="append", default=[])
    repair_packet.add_argument("--minimal-change", action="append", required=True)
    repair_packet.add_argument("--prohibited-change", action="append", default=[])
    repair_packet.add_argument(
        "--required-skill",
        default="tdd",
        choices=["tdd", "diagnose", "grill-with-docs", "improve-codebase-architecture", "evidence-only", "none"],
    )
    repair_packet.add_argument("--verification-command", action="append", required=True)
    repair_packet.add_argument("--evidence-required", action="append", default=[])
    repair_packet.add_argument("--stop-condition", default="Stop after this packet is satisfied or after three failed attempts.")
    repair_packet.set_defaults(func=cmd_repair_packet)

    github_control = subcommands.add_parser("github", help="Create GitHub evidence from Shiki state")
    github_subcommands = github_control.add_subparsers(dest="github_command", required=True)
    github_issue = github_subcommands.add_parser("issue", help="Create a GitHub issue for a Shiki task")
    github_issue.add_argument("--target", default=".", help="Target repository path")
    github_issue.add_argument("--task-id", required=True)
    github_issue.set_defaults(func=cmd_github_issue)
    github_pr = github_subcommands.add_parser("pr", help="Create a GitHub PR for a Shiki task")
    github_pr.add_argument("--target", default=".", help="Target repository path")
    github_pr.add_argument("--task-id", required=True)
    github_pr.add_argument("--base", default="main")
    github_pr.add_argument("--head")
    github_pr.set_defaults(func=cmd_github_pr)

    handoff = subcommands.add_parser("handoff", help="Write Codex handoff documents from Shiki state")
    handoff_subcommands = handoff.add_subparsers(dest="handoff_command", required=True)
    handoff_task = handoff_subcommands.add_parser("task", help="Write a Codex task handoff")
    handoff_task.add_argument("--target", default=".", help="Target repository path")
    handoff_task.add_argument("task_id")
    handoff_task.set_defaults(func=cmd_handoff_task)
    handoff_repair = handoff_subcommands.add_parser("repair", help="Write a Codex repair handoff")
    handoff_repair.add_argument("--target", default=".", help="Target repository path")
    handoff_repair.add_argument("repair_id")
    handoff_repair.set_defaults(func=cmd_handoff_repair)

    task = subcommands.add_parser("task", help="Manage Shiki task state")
    task_subcommands = task.add_subparsers(dest="task_command", required=True)
    task_status = task_subcommands.add_parser("status", help="Set a task status and record ledger evidence")
    task_status.add_argument("--target", default=".", help="Target repository path")
    task_status.add_argument("task_id")
    task_status.add_argument("--status", required=True, choices=["planned", "ready", "running", "blocked", "review", "repair-needed", "done"])
    task_status.set_defaults(func=cmd_task_status)

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    if getattr(args, "public", False):
        args.private = False
    try:
        return args.func(args)
    except ShikiError as error:
        print(f"[shiki] error: {error}", file=sys.stderr)
        return 1
